name = "tiny-hub"
main = "src/index.ts"
compatibility_date = "2023-10-02"

[[kv_namespaces]]
binding = "TINYHUB_KV"
id = "7462e0ad9016452b8f96fc039aed57f3"

[[r2_buckets]]
binding = "TINYHUB_R2"
bucket_name = "tinyhub"

[[d1_databases]]
binding = "TINYHUB_DB"
database_name = "tinyhub"
database_id = "d7698f09-cdf8-4e63-8856-9486dcc5f4ce"

[vars]
NODE_ENV = "production"
